### ISSUE TITLE
unknown option "tcp_only"

### ISSUE THREAD

**Issue by Tuumke** [ich777/docker-DoH#1]
Server isnt running here :(

---Sucessfully downloaded configuration file 'doh-server-conf' located in the root directory of the container---
find: '/DoH/.cache': No such file or directory
---Starting Server---
2019/10/30 19:37:28 unknown option "tcp_only"
---Checking if DoH-Server is installed---
---DoH-Server found!---
---Version Check---
---Versions match! Installed: v2.2.1 | Preferred: v2.2.1---
---Preparing Server---
---Starting Server---
2019/10/30 19:37:32 unknown option "tcp_only"

**Comment by Tuumke** [comment]
I commented the tcp_only line with a #

**Comment by ich777** [comment]
Why would you do that?
This variable must be in the config set it to 'true' or 'false' only one of the two is allowed.

EDIT: oh, i see the owner changed the config, will fix this in the next few days, you also have to add 'udp:' infront of every ip adress in the upstream section.

**Comment by Tuumke** [comment]
But,.. using UDP disables the whole DOH/DOT setup? UDP isnt secure..

**Comment by ich777** [comment]
I think you don't know how this works, this container is only a "gateway" and it must somehow ask a regular DNS server where or what ip the requested address is encrypt it and forward it to the DOH client.

Eg:
Android phone (let's say with the app Intra - on iOS with DNS Cloak) requests a IP (encrypted) and sends it to the container then the container asks a regular DNS server (unencrypted) what IP the requested address is after that the container sends the IP (encrypted) back to the phone so that the phone can connect to the requested IP.

I use this container in combination with pihole so that i can filter all the ads completely and my phone has no extra work to do = longer battery life!

Also you don't have to use UDP you can also use TCP DNS servers.

**Comment by Tuumke** [comment]
Ah i thought the goal was to have the DOH-Server do an encrypted request to a DNS server that supports it so that your ISP cant monitor your DNS requests anymore :)
Thnx for you explanation

**Comment by ich777** [comment]
@Tuumke Now created a DoH-Client container, it's ready for download and now works the way you want it, you can also use also PiHole in front of the DoH-Client container to filter also Ad's

**Comment by Tuumke** [comment]
So this DoH docker is just the server? I thought that if you install DoH-server you also get a client :-O 
WIll give the client a go too.

I followed these tutorials:
1.  https://www.aaflalo.me/2018/10/tutorial-setup-dns-over-https-server/
2. https://www.aaflalo.me/2018/10/dns-over-https-with-pi-hole/#Conclusion
3. https://www.aaflalo.me/2019/03/dns-over-tls/

-edit-
think i might have mistaken the dns-crypt-proxy for DOH client

**Comment by ich777** [comment]
If you want to protect your home you have to setup the client, if you want to host your own DoH service like Cloudflare or Google you have to setup the client, i created two Containers because not everyone wants to host his own DoH service.

If you want to use it all in all with PiHole set it up like this:
1. DoH-Client and assign it a static IP eg: 192.168.1.8 (if you want to protect your internal network you need to set the primary DNS Server in your DHCP Server to 192.168.1.8 - keep in mind that this is withou Ad blocking with PiHole if you want it with Ad Blocking go to step two)
2. Set up PiHole and also assing it a static IP eg: 192.168.1.7 (set the primary DNS server inside PiHole to your DoH-Client 192.168.1.8 - if you want DoH encryption in your local network and also Ad Blocking set the primary DNS Server in your DHCP server to 192.168.1.8)
3. If you also want to secure your external devices with Ad Blocking you have to setup DoH-Server and point it like in this example to 192.168.1.7 - if you want it withou Ad Blocking to 192.168.1.8 keep in mind that if you want it without adblocking that you can use Cloudflares or Googles service directly.

I hope this is all clear to you.
(Like i said above not everyone needs a DoH-Server - for outside devices - that's why i split the two applications)

Also please post any further questions in the Unraid forums so that everyone can read them.
